export { default as Index } from "./Index/Index";
export { default as Home } from "./Home/Home";
export { default as Profile } from "./Profile/Profile";
export { default as Register } from "./Register/Register";
export { default as Friends } from "./Friends/Friends";
export { default as PostPage } from "./PostPage/PostPage";
export { default as ProtectedRoute } from './ProtectedRoute/ProtectedRoute';
export { default as LoginFacebook } from './FacebookLogin/FacebookLogin'
export { default as Photos } from "./Photos/Photos";
export { default as ProfileFriends } from "./ProfileFriends/ProfileFriends";